唔～
Cute-Dress/Dress pull request #122
Opened 2024-12-04 09:40 UTC by baiyan0707

晒图～
TG: https://t.me/baiyue_077
欢迎小男娘扩列～

2024-12-04 15:55 UTC, CuteDress requested changes

2024-12-04 15:55 UTC, CuteDress commented on B/baiyan/IMG_2905.JPG
稍微缩减一下图片大小？ʕ•ٹ•ʔ

2024-12-04 15:55 UTC, CuteDress commented on B/baiyan/IMG_2905.JPG
还有其他几张也是

2024-12-05 07:19 UTC, baiyan0707 commented
更新了图片大小。

2024-12-05 12:56 UTC, CuteDress commented
好！

2024-12-05 12:56 UTC, merged