添加一张半身和一张白丝~ Kira✨
Cute-Dress/Dress pull request #126
Opened 2024-12-22 03:03 UTC by Feather-P

尝试PR

2024-12-22 07:42 UTC, CuteDress requested changes

2024-12-22 07:42 UTC, CuteDress commented on F/FeatherP/FEA_0893.jpg
稍微压缩一点大小喵~😊

2024-12-22 09:42 UTC, Feather-P commented
压缩了再试试（

2024-12-23 03:40 UTC, CuteDress approved these changes
好！

2024-12-23 03:40 UTC, merged