回家了，穿下女装
Cute-Dress/Dress pull request #46
Opened 2023-12-09 14:25 UTC by Hatsushigure

啊，久违的感觉
话说裙子似乎有点大了呢，领结也没找到，等到学校再搭水手服拍几张吧(⁠≧⁠▽⁠≦⁠)

别问我怎么没有别的，孩子没钱，这些都是存货

2023-12-10 03:32 UTC, Hatsushigure commented
怎么 Greeting 炸了

2023-12-10 03:33 UTC, Hatsushigure commented
有人手贱改了 yml 文件吗

2023-12-10 05:50 UTC, CuteDress requested changes
好！
但是太大了！

2023-12-10 09:12 UTC, Hatsushigure commented
手机上不太方便压缩，电脑上再处理一下（）

2023-12-10 09:25 UTC, Hatsushigure commented
所以压完了是强制 push 吗 @CuteDress

2023-12-13 01:48 UTC, Hatsushigure commented
已经改了捏 @CuteDress

2023-12-17 05:17 UTC, CuteDress commented
> 所以压完了是强制 push 吗 @CuteDress

随意，我是 Squash Merge 的

（周末才有空看项目，抱歉 {{{(>_<)}}} ）

2023-12-17 05:17 UTC, merged